---
# tasks file for roles/tls
- name: Ensure ssl directory exists
  file:
    path: "{{ ssl_dir }}"
    state: directory
    mode: '0755'

- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ca_key }}"
    size: 2048
    type: RSA

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ ssl_dir }}/ca.csr"
    privatekey_path: "{{ ca_key }}"
    common_name: CSFCA
    country_name: RU
    state_or_province_name: VoronezhOblast
    locality_name: Voronezh
    organization_name: VoronezhStateUniversity
    organizational_unit_name: CSF

- name: Generate self-signed CA certificate
  community.crypto.x509_certificate:
    path: "{{ ca_cert }}"
    csr_path: "{{ ssl_dir }}/ca.csr"
    privatekey_path: "{{ ca_key }}"
    provider: selfsigned
    selfsigned_not_after: "+1024d"
    selfsigned_digest: sha256
    selfsigned_create_subject_key_identifier: always_create

- name: Generate server private key
  community.crypto.openssl_privatekey:
    path: "{{ server_key }}"
    size: 2048
    type: RSA

- name: Generate CSR
  community.crypto.openssl_csr:
    path: "{{ csr_file }}"
    privatekey_path: "{{ server_key }}"
    common_name:                task-service.local
    country_name:               RU
    state_or_province_name:     VoronezhOblast
    locality_name:              Voronezh
    organization_name:          VoronezhStateUniversity
    organizational_unit_name:   Student
    email_address:              aklysh2014@gmail.com
    extended_key_usage:
      - serverAuth
    key_usage:
      - digitalSignature
      - nonRepudiation
    basic_constraints:
      - "CA:FALSE"

- name: Create server certificate 
  community.crypto.x509_certificate:
    path: "{{ server_cert }}"
    csr_path: "{{ csr_file }}"
    ownca_path: "{{ ca_cert }}"
    ownca_privatekey_path: "{{ ca_key }}"
    provider: ownca
    ownca_not_after: "+365d"
    ownca_not_before: "+0s"
    ownca_digest: sha256
