version: "3.9"
services:
  backend:
    build: backend/
    environment:
#      MYSQL_HOST: "mysql_db:3306"
      MYSQL_HOST: "mysql_db"
      MYSQL_PORT: "3306"
      JWT_SECRET_TOKEN: "your_secret_token_here"
      CORS_ORIGIN_REGEX: "http([s])?:\\/\\/localhost:3002"
    ports:
      - "3001:3001"
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      SERVER_ORIGIN: "http://localhost:3001"
    ports:
      - "127.0.0.1:3002:3002"
    depends_on:
      - backend

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tradeoffer_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 10s
      retries: 10

  adminer:
#    используется версия fastcgi вместо adminer, потому что зависает при скачивании adminer
#    image: adminer
    image: adminer:fastcgi
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - "30000:8080"
    depends_on:
      - mysql_db
