all:
  children:
    tradeoffer_vagrant:

tradeoffer_vagrant:
  hosts:
    task-service.local:
      ansible_host: 10.10.30.10
      ansible_user: vagrant
      ansible_ssh_public_key_file: ./ssh_keys/lab
